[2025-05-15T05:39:38.942+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T05:39:37.827495+00:00 [queued]>
[2025-05-15T05:39:38.973+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T05:39:37.827495+00:00 [queued]>
[2025-05-15T05:39:38.977+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T05:39:39.047+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-15 05:39:37.827495+00:00
[2025-05-15T05:39:39.061+0000] {standard_task_runner.py:60} INFO - Started process 213 to run task
[2025-05-15T05:39:39.066+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'manual__2025-05-15T05:39:37.827495+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmpuw1azz6r']
[2025-05-15T05:39:39.075+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask fetch_and_store_weather
[2025-05-15T05:39:39.120+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T05:39:39.197+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T05:39:37.827495+00:00 [running]> on host d34e993fee47
[2025-05-15T05:39:39.316+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T05:39:37.827495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T05:39:37.827495+00:00'
[2025-05-15T05:39:42.506+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T05:39:46.324+0000] {logging_mixin.py:188} INFO - Error inserting data: 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
[2025-05-15T05:39:46.325+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-15T05:39:46.337+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250515T053937, start_date=20250515T053938, end_date=20250515T053946
[2025-05-15T05:39:46.382+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-15T05:39:46.404+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
